# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'getDoc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'BSImagePicker'
  pod 'DropDown'
  pod 'KeychainAccess'

  target 'getDocTests' do
    inherit! :search_paths
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'BSImagePicker'
    pod 'DropDown'
    pod 'KeychainAccess'
  end

  target 'getDocUITests' do
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'BSImagePicker'
    pod 'DropDown'
    pod 'KeychainAccess'
  end

end
